export const initialState = {
  user: null,
  allUsers: null,
  allBooks: null,
  allquiz: null,
  allVideos: null,
  videoFilter:null,
  filterTerm: "all",
  levelFilter:null,
  categoryFilter:null,
  alertType:null,
  isVideoPlaying :false,
  isBookViewing:false,
  videoIndex:0,
  bookIndex:0,
  videoCato:null,
};
